<a href="https://colab.research.google.com/github/subhiksha9/DataAnalysisLab/blob/main/Wine_Quality_red.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.	Download the dataset winequality-red.csv file( each column is separated by a semicolon (;)) from the UCI Machine Learning Repository

2.	Convert it to numPy array, name it as wines (leave the first row of the list) and specify the data type of array as float.

In [23]:
import pandas as pd
import numpy as np
wines=np.genfromtxt(r"winequality-red.csv",delimiter=";",skip_header=1,dtype=float)
print(wines)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


3.	Identify the shape of the array.

In [24]:
wines.shape

(1599, 12)

4.	Display the element at row 3 and column 4.

In [25]:
wines[2,3]

2.3

5.	 Display the first three items from the fourth column.

In [26]:
wines[0:3,3]

array([1.9, 2.6, 2.3])

6.	Display third column from each row.

In [27]:
wines[:,2]

array([0.  , 0.  , 0.04, ..., 0.13, 0.12, 0.47])

7.	Display fourth row.

In [28]:
wines[3]

array([11.2  ,  0.28 ,  0.56 ,  1.9  ,  0.075, 17.   , 60.   ,  0.998,
        3.16 ,  0.58 ,  9.8  ,  6.   ])

8.	Assign value 10 to 2nd row and 6th column element.

In [29]:
wines[1,5]=10
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

9.	Take the 10th column from wines array and name that slice as slice_new and assign value 666 to all elements of slice_new.

In [30]:
slice_new=wines[:,9]
slice_new[:]=666
slice_new
wines[:,9]

array([666., 666., 666., ..., 666., 666., 666.])

10.	Display wines array.

In [31]:
wines

array([[7.40e+00, 7.00e-01, 0.00e+00, ..., 6.66e+02, 9.40e+00, 5.00e+00],
       [7.80e+00, 8.80e-01, 0.00e+00, ..., 6.66e+02, 9.80e+00, 5.00e+00],
       [7.80e+00, 7.60e-01, 4.00e-02, ..., 6.66e+02, 9.80e+00, 5.00e+00],
       ...,
       [6.30e+00, 5.10e-01, 1.30e-01, ..., 6.66e+02, 1.10e+01, 6.00e+00],
       [5.90e+00, 6.45e-01, 1.20e-01, ..., 6.66e+02, 1.02e+01, 5.00e+00],
       [6.00e+00, 3.10e-01, 4.70e-01, ..., 6.66e+02, 1.10e+01, 6.00e+00]])

11.	Find the data type of wines array and Change the data type to int.

In [32]:
print(wines.dtype)
wines=wines.astype(int)
print(wines.dtype)

float64
int64


12.	Add 10 points to each quality score.

In [33]:
wines[:][11]=wines[:][11]+10

13.	Find the sum of all the elements in an array

In [34]:
print(np.sum(wines))

1210518


14.	Find the sum of all the values in every column.

In [36]:
np.sum(wines,axis=0)

array([  12599,      34,      11,    3360,      10,   25377,   74311,
            91,    4780, 1064944,   15979,    9022])

15.	Find the sum of all the values in every row.

In [37]:
np.sum(wines,axis=1)

array([736, 769, 761, ..., 763, 767, 755])

16.	Add the quality column to itself.

In [38]:
wines[:,10]=np.add(wines[:,10],wines[:,10])
wines

array([[  7,   0,   0, ..., 666,  18,   5],
       [  7,   0,   0, ..., 666,  18,   5],
       [  7,   0,   0, ..., 666,  18,   5],
       ...,
       [  6,   0,   0, ..., 666,  22,   6],
       [  5,   0,   0, ..., 666,  20,   5],
       [  6,   0,   0, ..., 666,  22,   6]])

17.	Multiply alcohol by quality.

In [42]:
wines[:,9]*wines[:,10]

array([11988, 11988, 11988, ..., 14652, 13320, 14652])

18.	Display which wines have a quality rating higher than 5.

In [43]:
wines[wines[:,10]>5,10]

array([18, 18, 18, ..., 22, 20, 22])

19.	Check if any wines have a quality rating equal to 10.

In [44]:
wines[wines[:,10]==10,10]

array([], dtype=int64)

20.	Select rows in wines where the quality is over 7

In [45]:
wines[wines[:,10]>7]

array([[  7,   0,   0, ..., 666,  18,   5],
       [  7,   0,   0, ..., 666,  18,   5],
       [  7,   0,   0, ..., 666,  18,   5],
       ...,
       [  6,   0,   0, ..., 666,  22,   6],
       [  5,   0,   0, ..., 666,  20,   5],
       [  6,   0,   0, ..., 666,  22,   6]])

21.	Display wines with alcohol greater than 10 and quality greater than 7.

In [46]:
wines[(wines[:,9]>10) & (wines[:,10]>7),9:11]

array([[666,  18],
       [666,  18],
       [666,  18],
       ...,
       [666,  22],
       [666,  20],
       [666,  22]])

22.	Change the shape of wines array.

In [47]:
wines=wines.reshape(12,1599)
wines.shape

(12, 1599)